In [1]:
import pandas as pd
import numpy as np

## Concatenate Numpy

In [5]:
pd.options.display.float_format = '{:.2f}'.format    #Dar formato a los numeros con dos numeros decimales con Pandas 

In [31]:
np.set_printoptions(precision=1)        #Dar formato a los numeros con un numero decimal con Numpy

In [10]:
x1 = np.random.rand(2,5)*10          #rand genera num + entre 0 y 1 y randn entre 0 y -1
x1

array([[3.6, 5.9, 8.1, 3.9, 8.6],
       [0.9, 7.6, 4.9, 9.1, 2.6]])

In [11]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.3, -0.5, -0.4, -0.2, -1. ],
       [-0.3, -0.6, -0.2, -0.7, -0.1]])

In [12]:
np.concatenate([x1,x2])      #Se concatena en columnas 

array([[ 3.6,  5.9,  8.1,  3.9,  8.6],
       [ 0.9,  7.6,  4.9,  9.1,  2.6],
       [-0.3, -0.5, -0.4, -0.2, -1. ],
       [-0.3, -0.6, -0.2, -0.7, -0.1]])

In [13]:
np.concatenate([x1,x2]).shape

(4, 5)

In [14]:
np.concatenate([x1,x2], axis = 1)   #Se concatena en dimensiones o filas

array([[ 3.6,  5.9,  8.1,  3.9,  8.6, -0.3, -0.5, -0.4, -0.2, -1. ],
       [ 0.9,  7.6,  4.9,  9.1,  2.6, -0.3, -0.6, -0.2, -0.7, -0.1]])

In [15]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

## Concat Pandas Series 

In [16]:
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   3.62
b   5.94
c   8.10
d   3.86
e   8.65
dtype: float64

In [17]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.27
d   -0.47
e   -0.41
f   -0.21
g   -0.99
dtype: float64

In [18]:
pd.concat([s1,s2], axis=1)

0     1
a 3.62   nan
b 5.94   nan
c 8.10 -0.27
d 3.86 -0.47
e 8.65 -0.41
f  nan -0.21
g  nan -0.99

In [32]:
s1.reset_index()     #Quitamos el indice para poder concatenar bien 

index    0
0     a 3.62
1     b 5.94
2     c 8.10
3     d 3.86
4     e 8.65

In [19]:
s1.reset_index(drop=True)       #Aqui lo quitamos bien 

0   3.62
1   5.94
2   8.10
3   3.86
4   8.65
dtype: float64

In [20]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)     #Y ahora si se concatena 

0     1
0 3.62 -0.27
1 5.94 -0.47
2 8.10 -0.41
3 3.86 -0.21
4 8.65 -0.99

## Concat Pandas Dataframe 

In [21]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 1.21 8.71
1 2.81 2.91
2 2.95 4.94

In [22]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.20 -0.58
3 -0.12 -0.82
4 -0.53 -0.52

In [23]:
pd.concat([df1,df2])      #Concat columnas 

a     b
0  1.21  8.71
1  2.81  2.91
2  2.95  4.94
2 -0.20 -0.58
3 -0.12 -0.82
4 -0.53 -0.52

In [24]:
pd.concat([df1,df2], axis=1)    #Filas axis=1

a    b     a     b
0 1.21 8.71   nan   nan
1 2.81 2.91   nan   nan
2 2.95 4.94 -0.20 -0.58
3  nan  nan -0.12 -0.82
4  nan  nan -0.53 -0.52

In [25]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 2.95 4.94 -0.20 -0.58

In [26]:
pd.concat([                                          #Para cuando se tiene indices repetidos y no nos deja concatenar exacto se resetea el index
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 1.21 8.71 -0.20 -0.58
1 2.81 2.91 -0.12 -0.82
2 2.95 4.94 -0.53 -0.52

In [27]:
df1.append(df2).append(df2)          #Otra forma de concatenar

a     b
0  1.21  8.71
1  2.81  2.91
2  2.95  4.94
2 -0.20 -0.58
3 -0.12 -0.82
4 -0.53 -0.52
2 -0.20 -0.58
3 -0.12 -0.82
4 -0.53 -0.52

In [28]:
df1.T

0    1    2
a 1.21 2.81 2.95
b 8.71 2.91 4.94

In [30]:
df1.T.append(df2.T).T

a    b     a     b
0 1.21 8.71   nan   nan
1 2.81 2.91   nan   nan
2 2.95 4.94 -0.20 -0.58
3  nan  nan -0.12 -0.82
4  nan  nan -0.53 -0.52